language: c
compiler: 
  - cpp
before_script:
  - sudo apt-get install gnome-common gtk-doc-tools libglib2.0-dev libgtk2.0-dev libgconf2-dev build-essential python autoconf
script:
  - ./autogen.sh && ./configure && make
