sudo: false

language: python

python:
    # - "2.6": python 2.6 doesn't work with python-vte package
    "2.7"
    # - "3.2": python 33 fails in travis due to missing Python.h

virtualenv:
    system_site_packages: true

compiler:
    - gcc

addons:
  apt:
    sources:
        - deadsnakes
    packages:
        - autoconf
        - build-essential
        - gnome-common
        - gtk-doc-tools
        - libgconf2-dev
        - libglib2.0-dev
        - libgtk2.0-dev
        - python
        - python-appindicator
        - python-gtk2
        - python-gtk2-dev
        - python-vte
        - python3-dev

install:
    - pip install --upgrade pip
    - pip install -r python-requirements.txt
    - find /usr/include

script:
    - ./validate.sh
    - ./autogen.sh
    - ./configure && make
